import type { SampleReceiptOption } from '../types/bill';

export const SAMPLE_RECEIPTS: SampleReceiptOption[] = [
  {
    id: 'cafe-bill',
    title: 'Blue Tokai Cafe',
    subtitle: '4 Items • ₹1,320.00 • Cafe Check',
    category: 'cafe',
    imageUrl: '/samples/sample_receipt_cafe.png',
    filename: 'sample_receipt_cafe.png',
    data: {
      items: [
        {
          id: 'item_1',
          name: 'Iced Americano (Large)',
          quantity: 2,
          unit_price: 240.0,
          total_price: 480.0,
          confidence: 0.98,
        },
        {
          id: 'item_2',
          name: 'Butter Croissant',
          quantity: 1,
          unit_price: 180.0,
          total_price: 180.0,
          confidence: 0.96,
        },
        {
          id: 'item_3',
          name: 'Avocado Sourdough Toast',
          quantity: 1,
          unit_price: 380.0,
          total_price: 380.0,
          confidence: 0.92,
        },
        {
          id: 'item_4',
          name: 'Chocolate Brownie Sundae',
          quantity: 1,
          unit_price: 280.0,
          total_price: 280.0,
          confidence: 0.89,
        },
      ],
      subtotal: 1320.0,
      tax: 66.0,
      service_charge: 66.0,
      tip: 50.0,
      discount: 0.0,
      total: 1502.0,
      currency: 'INR',
      confidence_overall: 0.96,
    },
  },
  {
    id: 'restaurant-bill',
    title: 'Punjab Grill Bistro',
    subtitle: '5 Items • ₹2,450.00 • Dinner Check',
    category: 'restaurant',
    imageUrl: '/samples/sample_receipt_restaurant.png',
    filename: 'sample_receipt_restaurant.png',
    data: {
      items: [
        {
          id: 'item_1',
          name: 'Paneer Butter Masala',
          quantity: 1,
          unit_price: 450.0,
          total_price: 450.0,
          confidence: 0.95,
        },
        {
          id: 'item_2',
          name: 'Dal Makhani Bukhara',
          quantity: 1,
          unit_price: 420.0,
          total_price: 420.0,
          confidence: 0.94,
        },
        {
          id: 'item_3',
          name: 'Butter Garlic Naan',
          quantity: 4,
          unit_price: 90.0,
          total_price: 360.0,
          confidence: 0.88,
        },
        {
          id: 'item_4',
          name: 'Murgh Dum Biryani',
          quantity: 2,
          unit_price: 520.0,
          total_price: 1040.0,
          confidence: 0.91,
        },
        {
          id: 'item_5',
          name: 'Fresh Mint Lime Soda',
          quantity: 2,
          unit_price: 90.0,
          total_price: 180.0,
          confidence: 0.72,
        },
      ],
      subtotal: 2450.0,
      tax: 122.5,
      service_charge: 122.5,
      tip: 100.0,
      discount: 150.0,
      total: 2645.0,
      currency: 'INR',
      confidence_overall: 0.91,
    },
  },
  {
    id: 'grocery-bill',
    title: "Nature's Basket Supermarket",
    subtitle: '5 Items • ₹1,125.00 • Grocery',
    category: 'grocery',
    imageUrl: '/samples/sample_receipt_grocery.png',
    filename: 'sample_receipt_grocery.png',
    data: {
      items: [
        {
          id: 'item_1',
          name: 'Organic Almond Milk 1L',
          quantity: 2,
          unit_price: 260.0,
          total_price: 520.0,
          confidence: 0.97,
        },
        {
          id: 'item_2',
          name: 'Imported Hass Avocados',
          quantity: 2,
          unit_price: 160.0,
          total_price: 320.0,
          confidence: 0.84,
        },
        {
          id: 'item_3',
          name: 'Whole Grain Sourdough Loaf',
          quantity: 1,
          unit_price: 145.0,
          total_price: 145.0,
          confidence: 0.76,
        },
        {
          id: 'item_4',
          name: 'Greek Yogurt Blueberry 200g',
          quantity: 1,
          unit_price: 90.0,
          total_price: 90.0,
          confidence: 0.65,
        },
        {
          id: 'item_5',
          name: 'Reusable Eco Carry Bag',
          quantity: 1,
          unit_price: 50.0,
          total_price: 50.0,
          confidence: 0.45,
        },
      ],
      subtotal: 1125.0,
      tax: 56.25,
      service_charge: 0.0,
      tip: 0.0,
      discount: 50.0,
      total: 1131.25,
      currency: 'INR',
      confidence_overall: 0.86,
    },
  },
];
